config/routes.rb
Rails.application.routes.draw do

  resources :pictures do
    resources :comments
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/inbox'
  end
  
  resources :users
  
  resources :sessions, only:[:new, :create, :destroy]
  
  resources :favorites, only: [:create, :destroy]
  
  resources :tops, only: [:index]
  
  root to: 'tops#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :picture
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  
  validates :name, presence: true
  validates :email, presence: true,  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  
  has_secure_password
  validates :password, presence: true
  
  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
  
  has_many :following, through: :active_relationship, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @picture = Picture.find(params[:picture_id])
    
    @comment = @picture.comments.build(comment_params)
    
    respond_to do |format|
      if @comment.save
        format.js { render :index}
      else 
        format.html { redirect_to picture_path(@picture), notice: "投稿エラー"}
      end
    end
  end
  
  
  private
  
  def comment_params
    params.require(:comment).permit(:picture_id, :content)
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの写真をお気に入りしました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの写真をお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :login, only: [:new, :edit, :show, :destroy, :update]
  before_action :authenticate_picture, only: [:edit, :destroy, :update]


  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
    
    @comment = @picture.comments.build
    @comments = @picture.comments
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id

    respond_to do |format|
      if @picture.save
        PictureMailer.picture_mail(@picture).deliver
        format.html { redirect_to @picture, notice: '写真を投稿しました.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:image, :content, :image_cache, :user_id)
    end
    
    def login
      if not logged_in? 
        redirect_to new_session_path
      end
    end
    
    def authenticate_picture
      if current_user.id != @picture.user.id
         redirect_to pictures_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウト完了"
    redirect_to new_session_path
  end
  
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
    @favorite_pictures = @user.favorite_pictures
  end
  
  def destroy
    
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
  
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [picture, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> エラー:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
  

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <li>
        <p><%= comment.content %></p>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.picture.comments, picture: @comment.picture }) %>")
$("textarea").val('')

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogInsta</title>
    <%= csrf_meta_tags %>
    
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>New Age - Start Bootstrap Theme</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link rel="stylesheet" href="vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="vendor/simple-line-icons/css/simple-line-icons.css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="device-mockups/device-mockups.min.css">

    <!-- Custom styles for this template -->
    <link href="css/new-age.min.css" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>


    
  <% if controller.controller_name != "tops" %>
    <body class="usiro">
  <% else %>
    <body>
  <% end %>
    
    <%# flash.each do |key, value| %>
      <%#= content_tag(:div, value, class: "#{key}") %>
    <%# end %>
      
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id), class:"btn btn-outline btn-xl js-scroll-trigger" %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete, class:"btn btn-outline btn-xl js-scroll-trigger" %>
    <% else %>
      <%= link_to "Sign up", new_user_path, class:"btn btn-outline btn-xl js-scroll-trigger" %>
      <%= link_to "Login",  new_session_path, class:"btn btn-outline btn-xl js-scroll-trigger" %>
      <%= link_to "Top", tops_path, class:"btn btn-outline btn-xl js-scroll-trigger" %>
    <% end %>
    
      
    <div class="container">
      <%= yield %>
    </div>
      
    
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :picture_image %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :picture_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path, class:"btn btn-outline btn-xl js-scroll-trigger" %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>みんなの写真</h1>


<div class="row">
    <% @pictures.each do |picture| %>
      <div class="col-xs-12 col-md-6">
        <div class="row">
          <div class="col-xs-12 col-md-6">
            <%= image_tag picture.image, class: "photo" %>
          </div>
          <div class="col-md-4">
            <div class="row">
              <div class="col-xs-3 col-md-12"><%= picture.user.name %>さんの写真</div>
              <div class="col-xs-3 col-md-12"><%= link_to 'Show', picture, class:"btn btn-outline btn-xl js-scroll-trigger" %></div>
              <% if current_user.id == picture.user.id %>
                <div class="col-xs-3 col-md-12"><%= link_to 'Edit', edit_picture_path(picture), class:"btn btn-outline btn-xl js-scroll-trigger" %></div>
                <div class="col-xs-3 col-md-12"><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-outline btn-xl js-scroll-trigger"%></div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>

<br>
<br>

<%= link_to 'New Picture', new_picture_path, class:"btn btn-outline btn-xl js-scroll-trigger" %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @picture.image, class: "photo" %>
</p>

<p>
  <strong>Content:</strong>
  <%= @picture.content %>
</p>

<P>コメント一覧</P>
<div id="comment_area">
  <%= render partial: 'comments/index', locals: { comments: @comments, picture: @picture } %>
</div>
<div id="comment_form">
  <%= render partial: 'comments/form', locals: { comment: @comment, picture: @picture } %>
</div>

<% unless @picture.user == current_user %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入り', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_picture_path(@picture) %>
<%= link_to 'Back', pictures_path, class:"btn btn-outline btn-xl js-scroll-trigger" %>

app/views/tops/index.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>New Age - Start Bootstrap Theme</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link rel="stylesheet" href="vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="vendor/simple-line-icons/css/simple-line-icons.css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="device-mockups/device-mockups.min.css">

    <!-- Custom styles for this template -->
    <link href="css/new-age.min.css" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Instaもどき</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#download">Download</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#features">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <header class="masthead">
      <div class="container h-100">
        <div class="row h-100">
          <div class="col-lg-7 my-auto">
            <div class="header-content mx-auto">
              <h1 class="mb-5">Insta的なアプリです</h1>
              <a href="sessions/new" class="btn btn-outline btn-xl js-scroll-trigger">Log in</a>
            　<a href="users/new" class="btn btn-outline btn-xl js-scroll-trigger">Sign up</a>
            </div>
          </div>
          <div class="col-lg-5 my-auto">
            <div class="device-container">
              <div class="device-mockup iphone6_plus portrait white">
                <div class="device">
                  <div class="screen">
                    <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                    <img src="img/demo-screen-1.jpg" class="img-fluid" alt="">
                  </div>
                  <div class="button">
                    <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>

    <section class="download bg-primary text-center" id="download">
      <div class="container">
        <div class="row">
          <div class="col-md-8 mx-auto">
            <h2 class="section-heading">Discover what all the buzz is about!</h2>
            <p>Our app is available on any mobile device! Download now to get started!</p>
            <div class="badges">
              <a class="badge-link" href="#"><img src="img/google-play-badge.svg" alt=""></a>
              <a class="badge-link" href="#"><img src="img/app-store-badge.svg" alt=""></a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="features" id="features">
      <div class="container">
        <div class="section-heading text-center">
          <h2>Unlimited Features, Unlimited Fun</h2>
          <p class="text-muted">Check out what you can do with this app theme!</p>
          <hr>
        </div>
        <div class="row">
          <div class="col-lg-4 my-auto">
            <div class="device-container">
              <div class="device-mockup iphone6_plus portrait white">
                <div class="device">
                  <div class="screen">
                    <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                    <img src="img/demo-screen-1.jpg" class="img-fluid" alt="">
                  </div>
                  <div class="button">
                    <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-8 my-auto">
            <div class="container-fluid">
              <div class="row">
                <div class="col-lg-6">
                  <div class="feature-item">
                    <i class="icon-screen-smartphone text-primary"></i>
                    <h3>Device Mockups</h3>
                    <p class="text-muted">Ready to use HTML/CSS device mockups, no Photoshop required!</p>
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="feature-item">
                    <i class="icon-camera text-primary"></i>
                    <h3>Flexible Use</h3>
                    <p class="text-muted">Put an image, video, animation, or anything else in the screen!</p>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-6">
                  <div class="feature-item">
                    <i class="icon-present text-primary"></i>
                    <h3>Free to Use</h3>
                    <p class="text-muted">As always, this theme is free to download and use for any purpose!</p>
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="feature-item">
                    <i class="icon-lock-open text-primary"></i>
                    <h3>Open Source</h3>
                    <p class="text-muted">Since this theme is MIT licensed, you can use it commercially!</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="cta">
      <div class="cta-content">
        <div class="container">
          <h2>Stop waiting.<br>Start building.</h2>
          <a href="/sessions/new" class="btn btn-outline btn-xl js-scroll-trigger">Log in</a>
          <a href="/users/new" class="btn btn-outline btn-xl js-scroll-trigger">Sign up</a>
        </div>s
      </div>
      <div class="overlay"></div>
    </section>

    <section class="contact bg-primary" id="contact">
      <div class="container">
        <h2>We
          <i class="fa fa-heart"></i>
          new friends!</h2>
        <ul class="list-inline list-social">
          <li class="list-inline-item social-twitter">
            <a href="#">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
          <li class="list-inline-item social-facebook">
            <a href="#">
              <i class="fa fa-facebook"></i>
            </a>
          </li>
          <li class="list-inline-item social-google-plus">
            <a href="#">
              <i class="fa fa-google-plus"></i>
            </a>
          </li>
        </ul>
      </div>
    </section>

    <footer>
      <div class="container">
        <p>&copy; Your Website 2018. All Rights Reserved.</p>
        <ul class="list-inline">
          <li class="list-inline-item">
            <a href="#">Privacy</a>
          </li>
          <li class="list-inline-item">
            <a href="#">Terms</a>
          </li>
          <li class="list-inline-item">
            <a href="#">FAQ</a>
          </li>
        </ul>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="js/new-age.min.js"></script>

  </body>

</html>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
  
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<% if logged_in? %>
  <%= link_to 'みんなの写真へ', pictures_path, class:"btn btn-outline btn-xl js-scroll-trigger" %>
<% else %>
  <%= link_to "ログイン", new_session_path, class:"btn btn-outline btn-xl js-scroll-trigger" %>
<% end %>


<br>


<% @favorite_pictures.each do |picture| %>
　<p>あなたがお気に入りした写真</p>
  <p>
    <tr>
      <td><%= image_tag picture.image, class: "photo" %></td>
      <td><%= link_to '詳細', picture_path(picture.id), class:"btn btn-outline btn-xl js-scroll-trigger" %></td>
    </tr>
  </p>
<% end %>